//! Direct bindings to the C interface of Live2D Cubism SDK Core for Native.

#![cfg(not(target_arch = "wasm32"))]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// Include bindings generated by build.rs
// OUT_DIR is set by Cargo during build script execution
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

